version: '3'

volumes:
  data:

networks:
  ums-back-office:
  ums-user-facing:

services:
  db:
    image: mariadb
    container_name: dd-db
    volumes:
      - data:/var/lib/mysql
    networks:
      - ums-back-office
    environment:
      MARIADB_ROOT_PASSWORD: devpass
      MARIADB_DATABASE: ums
      MARIADB_USER: dev
      MARIADB_PASSWORD: devpass

  redis:
    image: redis:7.2.1-alpine
    restart: always
    networks:
      - ums-back-office

  backend:
    image: demo
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    container_name: dd-backend
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - ums-back-office
      - ums-user-facing
    environment:
      UMS_DB_NAME: ums
      UMS_DB_USERNAME: dev
      UMS_DB_PASSWORD: devpass
      UMS_DB_PORT: 3306
      UMS_DB_IP: db

  frontend:
    image: fedemo
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    container_name: dd-frontend
    networks:
      - ums-user-facing

  nginx:
    image: nginx:1.25.2-alpine3.18-slim
    container_name: dd-nginx
    ports:
      - "7887:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - ums-user-facing
